version: '3'
services:
  giligili:
    image: golang:latest
    container_name: giligili
    expose:
    - "80"
    environment:
    - VIRTUAL_HOST=sjs.ngrok.hanwide.com
    - GOPROXY=http://mirrors.aliyun.com/goproxy/
    - GO111MODOLE=on
    volumes:
      - ./:/go/src/giligili
    command: go run /go/src/giligili/main.go
    network_mode: docker_network